#!/usr/bin/env bash
#
# scripts/prod.sh — production launcher for `docker-compose.prod.yml`.
#
# One entry point for the whole prod lifecycle:
#   1. Optionally (re)build the env file deploy/.env.prod — prompts for the
#      handful of values only you can provide (domain, admin email/password,
#      LLM provider + key, Telegram token, web-search backend) and
#      RANDOM-GENERATES the rest (Postgres password, JWT / session / metrics
#      secrets, object-store keys, one invitation token per agent). Skip this
#      to reuse the existing env file.
#   2. Run a compose action against that env file: start / restart / stop.
#
# The `search` compose profile (the bundled SearXNG) is auto-added to start /
# restart whenever the env file's SUITE_SEARXNG_URL is the bundled
# http://searxng:8080 — no flag to remember.
#
# Usage:
#   scripts/prod.sh                  # interactive: build env? -> action
#   OUT=/path/to/.env scripts/prod.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${OUT:-deploy/.env.prod}"
COMPOSE_FILE="docker-compose.prod.yml"
# Compose override layered on ONLY for EDGE_MODE=ip: drops the base file's
# domain ports (80/443) so caddy publishes just the dedicated bare-IP ports.
IP_PORTS_OVERRIDE="deploy/compose.ip-ports.yml"
BUNDLED_SEARXNG_URL="http://searxng:8080"
DEFAULT_ROUTER_HTTPS_PORT="443"    # router + admin port identity for bare-IP LAN
DEFAULT_WEBAPP_HTTPS_PORT="8443"   # webapp's port identity for bare-IP LAN
# build_env always (re)generates the Caddyfile here and points
# CADDYFILE_HOST_PATH (compose's caddy bind mount) at it — one code path for all
# edge modes. The committed deploy/Caddyfile stays the localhost default for a
# bare `docker compose up` without prod.sh. Gitignored (see .gitignore).
CADDYFILE_GENERATED="./deploy/Caddyfile.generated"

# Set to 1 once invitation tokens have been minted in THIS invocation (by
# build_env). start/restart then skip their own refresh so tokens are
# generated exactly once per launch — never twice (see refresh_invitations).
TOKENS_MINTED=0

# URL-/DSN-/JSON-safe secret of $1 chars (alphanumeric only).
gen() { openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | head -c "${1:-44}"; }

# Read a single VAR's value from an existing env file (empty if absent/missing).
# Used to CARRY FORWARD secrets that get baked into persistent volumes on first
# use (PG_PASSWORD → pg_data, S3 keys → seaweedfs_data): Postgres/SeaweedFS only honor
# them when the volume is EMPTY (first init), so regenerating them on an env
# rebuild while the volume survives a non-reset relaunch would break auth
# (migrate: password authentication failed → exit 1). Caller falls back to
# `gen` only when this returns empty (first build, or after `reset`/down -v).
env_val() {  # env_val <VAR> [file]
    local f="${2:-$OUT}"
    [[ -f "$f" ]] || return 0
    sed -n "s/^$1=//p" "$f" | tail -n1
}

# Keep a volume-baked secret: reuse the existing file's value if present, else
# mint a fresh one. Echoes the value (for capture).
keep_or_gen() {  # keep_or_gen <VAR> <gen-length>
    local cur; cur="$(env_val "$1")"
    if [[ -n "$cur" ]]; then printf '%s' "$cur"; else gen "$2"; fi
}

ask() {  # ask <var> <prompt> <default>
    local var="$1" prompt="$2" def="${3:-}" reply
    if [[ -n "$def" ]]; then read -rp "$prompt [$def]: " reply || true
    else read -rp "$prompt: " reply || true; fi
    printf -v "$var" '%s' "${reply:-$def}"
}

yesish() { [[ "${1,,}" =~ ^(y|yes)$ ]]; }

# Marker on a prod.sh-generated overlay — lets a later run tell its own output
# (safe to regenerate) from an operator's hand-edited overlay (never clobbered).
OVERLAY_SENTINEL="// GENERATED by scripts/prod.sh — safe to regenerate; add extra presets via /admin."

# Generate the operator overlay (deploy/presets.custom.jsonc) repointing the
# `default` + `default_embedding` presets at the chosen provider, with the
# embedding dimension PINNED so it matches SUITE_EMBEDDING_DIM. The pinned-field
# re-sync re-applies these entries every boot while leaving operator edits to
# OTHER fields (tier gate, etc.) intact. Clobber-safe: writes the real overlay
# only when it's absent, the unmodified .example seed, or a previous prod.sh
# output (sentinel on line 1); otherwise writes a `.generated` sibling and asks
# the operator to merge. Uses the module-level PROVIDER/BALANCED_MODEL/EMBED_*
# and EMBEDDING_DIM set by build_env. No-op for the custom provider.
generate_overlay() {
    local target="deploy/presets.custom.jsonc" body
    body="$(cat <<JSONC
$OVERLAY_SENTINEL
// Repoints default + default_embedding at this deploy's provider ($PROVIDER).
// Add any other presets in /admin (admin-created presets are never re-synced).
[
  {
    "name": "default",
    "provider": "$PROVIDER",
    "concrete_model": "$BALANCED_MODEL",
    "api_key_ref": "env://$KEY_VAR"
  },
  {
    "name": "default_embedding",
    "provider": "$EMBED_PROVIDER",
    "concrete_model": "$EMBED_MODEL",
    "api_key_ref": "env://$EMBED_KEY_VAR",
    "default_provider_options": { "$EMBED_OPT": $EMBEDDING_DIM }
  }
]
JSONC
)"
    if [[ ! -f "$target" ]] \
        || head -n1 "$target" | grep -qxF "$OVERLAY_SENTINEL" \
        || { [[ -f "$target.example" ]] && cmp -s "$target" "$target.example"; }; then
        printf '%s\n' "$body" > "$target"
        chmod 600 "$target"
        echo "  generated $target (default→$PROVIDER/$BALANCED_MODEL;" \
             "default_embedding→$EMBED_PROVIDER/$EMBED_MODEL, dim $EMBEDDING_DIM)."
    else
        printf '%s\n' "$body" > "$target.generated"
        chmod 600 "$target.generated"
        echo "  NOTE: $target has operator edits — left untouched. Wrote the"
        echo "        suggested default/default_embedding entries to"
        echo "        $target.generated; merge them in (or delete your overlay to"
        echo "        let prod.sh manage it)."
    fi
}

# ---------------------------------------------------------------------------
# Step 1 — build the env file (first deploy, or to change vars)
# ---------------------------------------------------------------------------
build_env() {
    echo "Generating $OUT — answer a few prompts; the rest is auto-generated."
    # Edge / reverse proxy (Caddy). The stack can be reached by a DOMAIN identity
    # (router + admin on PUBLIC_DOMAIN; browser channel on WEBAPP_DOMAIN — a
    # separate host because the webapp serves from / and would collide with the
    # router's /admin), by a bare-IP identity (LAN, no DNS), or BOTH at once.
    # prod.sh GENERATES the Caddyfile from the answers (CADDYFILE_GENERATED) —
    # serving two identities at once is why it's generated, not env-templated.
    # See docs/backplaned/deployment.md "Edge / reverse proxy (Caddy)".
    echo
    echo "Edge / reverse proxy (Caddy) — how is this stack reached?"
    echo "  1) Domain only       — a hostname: public domain, LAN name, or localhost"
    echo "  2) Bare IP only      — a LAN IP (e.g. 192.168.1.50); https via internal CA"
    echo "  3) Domain + bare IP  — both at once (e.g. a public domain via Cloudflare"
    echo "                         Tunnel AND direct LAN access by IP)"
    ask EDGE_MODE_CHOICE "Choose 1-3" "1"
    case "${EDGE_MODE_CHOICE,,}" in
        1|domain|"") EDGE_MODE=domain ;;
        2|ip)        EDGE_MODE=ip ;;
        3|both)      EDGE_MODE=both ;;
        *) echo "invalid edge mode: $EDGE_MODE_CHOICE" >&2; exit 1 ;;
    esac

    # Per-identity vars (empty for the identity this mode omits). PUBLIC_IP is
    # ALWAYS https (Caddy internal CA); only a DOMAIN can be served over http
    # (TLS terminated upstream).
    PUBLIC_DOMAIN=""; WEBAPP_DOMAIN=""; EDGE_SCHEME=https
    PUBLIC_IP=""; ROUTER_HTTPS_PORT=""; WEBAPP_HTTPS_PORT=""

    if [[ "$EDGE_MODE" == "domain" || "$EDGE_MODE" == "both" ]]; then
        echo
        echo "Domain identity (router + admin UI host, then the browser-channel host):"
        echo "  localhost            → this machine only (Caddy internal-CA / self-signed TLS)"
        echo "  a public domain      → auto-TLS via Let's Encrypt (must resolve here, 80/443 open)"
        echo "  a LAN name (bp.lan)  → LAN access; Caddy internal-CA TLS (browser trust needed)"
        ask PUBLIC_DOMAIN "Public domain — router + admin UI host" "localhost"
        ask WEBAPP_DOMAIN "Webapp (browser channel) host" "app.${PUBLIC_DOMAIN}"
        # Edge scheme. Default: Caddy terminates TLS (https). Answer y when TLS
        # is handled UPSTREAM — Cloudflare Tunnel, external LB, ngrok — so Caddy
        # serves plain HTTP at the origin (automatic HTTPS off). The PUBLIC
        # scheme stays https, so secrets/cookies are unaffected.
        echo
        echo "Is TLS terminated UPSTREAM for the domain (Cloudflare Tunnel / external LB)?"
        echo "If yes, Caddy serves plain HTTP at the origin instead of provisioning certs."
        ask UPSTREAM_TLS "TLS terminated upstream? [y/N]" "n"
        if yesish "$UPSTREAM_TLS"; then EDGE_SCHEME=http; else EDGE_SCHEME=https; fi
    fi

    if [[ "$EDGE_MODE" == "ip" || "$EDGE_MODE" == "both" ]]; then
        # A bare IP can't host app.<ip> (no DNS), so the webapp gets its OWN
        # https PORT on the same IP instead of a host. Always https: Caddy's
        # internal CA issues the IP cert (Let's Encrypt refuses IP literals) and
        # render-caddyfile.sh adds the global default_sni the no-SNI IP client
        # needs (see that script's header / docs §9).
        echo
        echo "Bare-IP identity (LAN access, no DNS — always https via Caddy's internal CA):"
        echo "  router + admin UI answer on https://<ip>:<router-port> (default 443); the"
        echo "  webapp gets its own https port (no DNS for app.<ip>) at https://<ip>:<port>."
        ask PUBLIC_IP "Bare IP (e.g. 192.168.1.50)" ""
        [[ "$PUBLIC_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || { echo "invalid IPv4 address: $PUBLIC_IP" >&2; exit 1; }
        ask ROUTER_HTTPS_PORT "Router + admin HTTPS port" "$DEFAULT_ROUTER_HTTPS_PORT"
        [[ "$ROUTER_HTTPS_PORT" =~ ^[0-9]+$ ]] \
            || { echo "router HTTPS port must be numeric: $ROUTER_HTTPS_PORT" >&2; exit 1; }
        ask WEBAPP_HTTPS_PORT "Webapp HTTPS port (separate from the router's $ROUTER_HTTPS_PORT)" "$DEFAULT_WEBAPP_HTTPS_PORT"
        [[ "$WEBAPP_HTTPS_PORT" =~ ^[0-9]+$ && "$WEBAPP_HTTPS_PORT" != "$ROUTER_HTTPS_PORT" ]] \
            || { echo "webapp HTTPS port must be numeric and != $ROUTER_HTTPS_PORT: $WEBAPP_HTTPS_PORT" >&2; exit 1; }
    fi

    # ROUTER_PUBLIC_URL — the canonical PUBLIC origin (always https, even when
    # the domain is served over http behind an upstream terminator). The domain
    # is canonical when present (domain/both); the IP otherwise.
    if [[ -n "$PUBLIC_DOMAIN" ]]; then
        ROUTER_PUBLIC_URL="https://$PUBLIC_DOMAIN"
    else
        ROUTER_PUBLIC_URL="https://$PUBLIC_IP"
    fi

    ask ADMIN_EMAIL "Bootstrap admin email" "admin@example.com"
    read -rsp "Bootstrap admin password (blank = generate one): " ADMIN_PW || true; echo

    # --- LLM provider -> API key -> per-tier preset aliases -----------------
    # Pick the provider for the default chat tiers, capture its key, and wire
    # the suite's lite/balanced/pro (+ embedding) defaults to that provider's
    # seeded preset aliases (see bp_router/llm/presets_catalog.jsonc).
    echo
    echo "LLM provider for the default chat tiers:"
    echo "  1) Anthropic (Claude)"
    echo "  2) Gemini (Google)"
    echo "  3) OpenAI (GPT)"
    echo "  4) Custom — wire the generic lite/default/pro slots; set models + keys"
    echo "             later via the admin webUI"
    ask PROVIDER_CHOICE "Choose 1-4" "2"
    case "${PROVIDER_CHOICE,,}" in
        1|anthropic) PROVIDER=anthropic ;;
        2|gemini)    PROVIDER=gemini ;;
        3|openai)    PROVIDER=openai ;;
        4|custom)    PROVIDER=custom ;;
        *) echo "invalid provider choice: $PROVIDER_CHOICE" >&2; exit 1 ;;
    esac

    # provider -> (key env var, lite/balanced/pro aliases, the balanced model
    # for `default`, and the embedding backend for `default_embedding`).
    # `custom` asks for the preset NAME backing each tier (default `default`)
    # and asks for no key — the operator brings their own presets via the admin
    # webUI or a deploy/presets.custom.jsonc overlay, and configures keys there.
    #
    # The bundled catalogue already carries the per-tier aliases (gemini-lite,
    # gpt, claude-opus, …) with correct provider/model/key; only `default` and
    # `default_embedding` need repointing at the chosen provider, which
    # generate_overlay() does. BALANCED_MODEL / EMBED_MODEL mirror
    # presets_catalog.jsonc — keep them in sync if the catalogue's models move.
    BALANCED_MODEL=""; EMBED_PROVIDER=""; EMBED_MODEL=""; EMBED_KEY_VAR=""; EMBED_OPT=""
    case "$PROVIDER" in
        anthropic)
            KEY_VAR=ANTHROPIC_API_KEY
            PRESET_LITE=claude-haiku; PRESET_BALANCED=claude; PRESET_PRO=claude-opus
            BALANCED_MODEL=claude-sonnet-4-6
            # Anthropic has no embeddings → OpenAI embeddings (separate key).
            EMBED_PROVIDER=openai-embeddings; EMBED_MODEL=text-embedding-3-small
            EMBED_KEY_VAR=OPENAI_API_KEY; EMBED_OPT=dimensions ;;
        gemini)
            KEY_VAR=GEMINI_API_KEY
            PRESET_LITE=gemini-lite; PRESET_BALANCED=gemini; PRESET_PRO=gemini-pro
            BALANCED_MODEL=gemini-3.5-flash
            EMBED_PROVIDER=gemini; EMBED_MODEL=gemini-embedding-2
            EMBED_KEY_VAR=GEMINI_API_KEY; EMBED_OPT=output_dimensionality ;;
        openai)
            KEY_VAR=OPENAI_API_KEY
            PRESET_LITE=gpt-nano; PRESET_BALANCED=gpt; PRESET_PRO=gpt-pro
            BALANCED_MODEL=gpt-5.5
            EMBED_PROVIDER=openai-embeddings; EMBED_MODEL=text-embedding-3-small
            EMBED_KEY_VAR=OPENAI_API_KEY; EMBED_OPT=dimensions ;;
        custom)
            KEY_VAR=""
            # Asked below. Default each tier to `default` — the one preset
            # guaranteed to exist in the bundled catalogue (and to survive a
            # custom overlay), so a fresh custom deploy still resolves.
            PRESET_LITE=default; PRESET_BALANCED=default; PRESET_PRO=default
            PRESET_EMBEDDING=default_embedding ;;
    esac
    # For a hosted provider the embedding tier always resolves `default_embedding`
    # (repointed by generate_overlay); custom names its own preset below.
    [[ "$PROVIDER" != custom ]] && PRESET_EMBEDDING=default_embedding

    # Custom provider: the operator brings their own presets (built-ins,
    # admin-webUI edits, or a deploy/presets.custom.jsonc overlay), so ask which
    # preset NAME backs each tier rather than hard-wiring a provider's models.
    # Default `default` (always available). No validation here — a name that
    # doesn't resolve surfaces at first use (PresetUnknownError); repoint it in
    # the admin webUI or the overlay.
    if [[ "$PROVIDER" == "custom" ]]; then
        echo
        echo "Custom provider: name the preset backing each model tier"
        echo "(must exist in the catalog / your overlay; 'default' always works)."
        ask PRESET_LITE "  lite tier preset name" "default"
        ask PRESET_BALANCED "  balanced tier preset name" "default"
        ask PRESET_PRO "  pro tier preset name" "default"
        ask PRESET_EMBEDDING "  embedding preset name" "default_embedding"
    fi

    # Embedding vector dimension. For a hosted provider it is PINNED onto
    # default_embedding's provider_options (the model emits exactly this width)
    # AND written to SUITE_EMBEDDING_DIM — so the two CANNOT drift. It is baked
    # into the KB/memory LanceDB schema (pa.list_(float32, dim)) on FIRST write
    # and frozen for the life of the lancedb_data volume (a later change needs a
    # reset). 1536 suits the bundled embedding models; pick another only if you
    # repoint default_embedding to a model with a different width.
    echo
    ask EMBEDDING_DIM "Embedding vector dimension (KB/memory vector width)" "1536"
    [[ "$EMBEDDING_DIM" =~ ^[0-9]+$ && "$EMBEDDING_DIM" -gt 0 ]] \
        || { echo "embedding dimension must be a positive integer: $EMBEDDING_DIM" >&2; exit 1; }

    if [[ -n "$KEY_VAR" ]]; then
        ask PROVIDER_KEY "$PROVIDER API key (resolves env://$KEY_VAR for the presets)" ""
    else
        PROVIDER_KEY=""
    fi
    # A SEPARATE embedding-provider key when it differs from the chat key — e.g.
    # Anthropic chat has no embeddings, so default_embedding uses OpenAI.
    EMBED_KEY=""
    if [[ -n "$EMBED_KEY_VAR" && "$EMBED_KEY_VAR" != "$KEY_VAR" ]]; then
        ask EMBED_KEY "Embedding API key (resolves env://$EMBED_KEY_VAR for default_embedding)" ""
    fi
    ask TELEGRAM "Telegram bot token (from @BotFather)" ""

    # --- Web search backend (research agent) --------------------------------
    # Pick the backend, then its config: searxng (bundled/external/none),
    # brave (LLM-Context API key), or kagi (FastGPT + Extract API key).
    # brave/kagi run an LLM under the hood; with no key research falls back to
    # SearXNG. Only the bundled SearXNG auto-adds the compose `search` profile.
    WEB_BACKEND="searxng"; SEARXNG_URL=""; BRAVE_KEY=""; KAGI_KEY=""
    echo
    echo "Web search backend for the research agent:"
    echo "  1) SearXNG (self-hosted metasearch)"
    echo "  2) Brave  (LLM-Context API — needs a Brave API key)"
    echo "  3) Kagi   (FastGPT + Extract — needs a Kagi API key)"
    ask WEB_BACKEND_CHOICE "Choose 1-3" "1"
    case "${WEB_BACKEND_CHOICE,,}" in
        1|searxng|"")
            WEB_BACKEND="searxng"
            echo
            echo "SearXNG instance:"
            echo "  1) Deploy SearXNG with compose (bundled 'search' profile)"
            echo "  2) Use an external SearXNG (you provide the URL)"
            echo "  3) Don't configure now (research runs without web search)"
            ask SEARXNG_CHOICE "Choose 1-3" "1"
            case "${SEARXNG_CHOICE,,}" in
                1|compose|bundled)
                    SEARXNG_URL="$BUNDLED_SEARXNG_URL" ;;
                2|external)
                    ask SEARXNG_URL "External SearXNG base URL (e.g. https://searx.example.com)" ""
                    [[ -z "$SEARXNG_URL" ]] && echo "  WARNING: empty URL — research will have no web search." ;;
                3|none|"")
                    SEARXNG_URL="" ;;
                *) echo "invalid search choice: $SEARXNG_CHOICE" >&2; exit 1 ;;
            esac ;;
        2|brave)
            WEB_BACKEND="brave"
            ask BRAVE_KEY "Brave API key (X-Subscription-Token)" ""
            [[ -z "$BRAVE_KEY" ]] && echo "  WARNING: empty key — research falls back to SearXNG." ;;
        3|kagi)
            WEB_BACKEND="kagi"
            ask KAGI_KEY "Kagi API key (FastGPT + Extract)" ""
            [[ -z "$KAGI_KEY" ]] && echo "  WARNING: empty key — research falls back to SearXNG." ;;
        *) echo "invalid backend choice: $WEB_BACKEND_CHOICE" >&2; exit 1 ;;
    esac

    local GENERATED_PW=0
    if [[ -z "$ADMIN_PW" ]]; then ADMIN_PW="$(gen 20)"; GENERATED_PW=1; fi

    # Volume-baked secrets: capture BEFORE the `{ } > "$OUT"` block truncates
    # the file. Reuse the existing value when a previous $OUT is present — so a
    # rebuild over SURVIVING data volumes keeps the secret the volume was
    # initialised with (else Postgres/SeaweedFS keep the OLD secret and the NEW one
    # in .env fails auth → migrate exit 1). Mint fresh only when $OUT is absent
    # (true first build). After `reset` (down -v) the volumes are gone but $OUT
    # remains, so the reused secret simply re-initialises the now-empty volume —
    # consistent either way. A reused-vs-minted count is reported after write.
    local PG_PW SUITE_DB_PW S3_AK S3_SK REUSED=0 MINTED=0
    PG_PW="$(keep_or_gen PG_PASSWORD 32)"
    SUITE_DB_PW="$(keep_or_gen SUITE_DB_PASSWORD 32)"
    S3_AK="$(keep_or_gen S3_ACCESS_KEY 20)"
    S3_SK="$(keep_or_gen S3_SECRET_KEY 40)"
    local _v
    for _v in PG_PASSWORD SUITE_DB_PASSWORD S3_ACCESS_KEY S3_SECRET_KEY; do
        if [[ -n "$(env_val "$_v")" ]]; then REUSED=$((REUSED+1)); else MINTED=$((MINTED+1)); fi
    done

    {
        echo "# Generated by scripts/prod.sh on $(date -u +%FT%TZ)."
        echo "# Compose interpolation vars for docker-compose.prod.yml. KEEP SECRET."
        echo
        echo "# --- Edge / reverse proxy (Caddy) ---"
        echo "# The Caddyfile is GENERATED for EDGE_MODE=$EDGE_MODE by"
        echo "# scripts/render-caddyfile.sh and written to CADDYFILE_HOST_PATH"
        echo "# (compose's caddy service bind-mounts it). Re-run scripts/prod.sh to"
        echo "# change the edge. domain → router+admin on PUBLIC_DOMAIN, browser"
        echo "# channel on WEBAPP_DOMAIN; ip → both on a bare IP (https, internal"
        echo "# CA), webapp on its own WEBAPP_HTTPS_PORT; both → serve both at once."
        echo "# See docs/backplaned/deployment.md."
        echo "EDGE_MODE=$EDGE_MODE"
        echo "CADDYFILE_HOST_PATH=$CADDYFILE_GENERATED"
        if [[ -n "$PUBLIC_DOMAIN" ]]; then
            echo "PUBLIC_DOMAIN=$PUBLIC_DOMAIN"
            echo "WEBAPP_DOMAIN=$WEBAPP_DOMAIN"
            if [[ "$EDGE_SCHEME" != "https" ]]; then
                echo "# TLS terminated upstream — Caddy serves plain HTTP at the origin."
                echo "EDGE_SCHEME=$EDGE_SCHEME"
            fi
        fi
        if [[ -n "$PUBLIC_IP" ]]; then
            echo "# Bare-IP identity — always https via Caddy's internal CA. The"
            echo "# router/admin and webapp each get their own published port (no"
            echo "# DNS for app.<ip>); the two ports must differ."
            echo "PUBLIC_IP=$PUBLIC_IP"
            echo "ROUTER_HTTPS_PORT=$ROUTER_HTTPS_PORT"
            echo "WEBAPP_HTTPS_PORT=$WEBAPP_HTTPS_PORT"
        fi
        echo "# Canonical PUBLIC origin (always https; the domain wins when present)."
        echo "ROUTER_PUBLIC_URL=$ROUTER_PUBLIC_URL"
        echo
        echo "# --- Postgres (router + suite DBs share this server; suite connects as postgres) ---"
        echo "PG_USER=postgres"
        echo "PG_PASSWORD=$PG_PW"
        echo "SUITE_DB_PASSWORD=$SUITE_DB_PW"
        echo
        echo "# --- Router secrets ---"
        echo "ROUTER_JWT_SECRET=$(gen 48)"
        echo "ROUTER_ADMIN_SESSION_SECRET=$(gen 48)"
        echo "ROUTER_METRICS_TOKEN=$(gen 32)"
        echo
        echo "# --- Webapp (browser channel) secrets ---"
        echo "WEBAPP_SESSION_SECRET=$(gen 48)"
        echo
        echo "# --- MCP bridge (service_mcp) — prod.sh auto-adds '--profile mcp' ---"
        echo "# The router seeds this as the bridge's refresh-token credential; the"
        echo "# mcp_bridge service presents the same value. Unset → bridge not run."
        echo "MCP_BRIDGE_SECRET=$(keep_or_gen MCP_BRIDGE_SECRET 48)"
        echo
        echo "# --- First-boot admin (idempotent seed) ---"
        echo "BOOTSTRAP_ADMIN_EMAIL=$ADMIN_EMAIL"
        echo "BOOTSTRAP_ADMIN_PASSWORD=$ADMIN_PW"
        echo
        echo "# --- Object store (SeaweedFS / S3) ---"
        echo "S3_BUCKET=bp-files"
        echo "S3_ACCESS_KEY=$S3_AK"
        echo "S3_SECRET_KEY=$S3_SK"
        echo
        echo "# --- LLM provider ($PROVIDER) + per-tier preset defaults ---"
        if [[ -n "$KEY_VAR" ]]; then
            echo "$KEY_VAR=$PROVIDER_KEY"
        else
            echo "# custom: set provider key(s) + define/repoint the tier presets"
            echo "# named above via the admin webUI (/admin) or a"
            echo "# deploy/presets.custom.jsonc overlay."
        fi
        # Separate embedding-provider key (e.g. Anthropic chat → OpenAI embeddings).
        if [[ -n "$EMBED_KEY_VAR" && "$EMBED_KEY_VAR" != "$KEY_VAR" ]]; then
            echo "# Embedding provider key — default_embedding resolves env://$EMBED_KEY_VAR."
            echo "$EMBED_KEY_VAR=$EMBED_KEY"
        fi
        echo "SUITE_DEFAULT_PRESET_LITE=$PRESET_LITE"
        echo "SUITE_DEFAULT_PRESET_BALANCED=$PRESET_BALANCED"
        echo "SUITE_DEFAULT_PRESET_PRO=$PRESET_PRO"
        echo "SUITE_DEFAULT_PRESET_EMBEDDING=$PRESET_EMBEDDING"
        echo "# Vector length the embedding preset emits — baked into the KB/memory"
        echo "# LanceDB schema on first write and frozen for the life of the"
        echo "# lancedb_data volume. For a hosted provider, prod.sh PINS this same"
        echo "# value on $PRESET_EMBEDDING (deploy/presets.custom.jsonc) so the model"
        echo "# emits exactly this width — keep the two in sync if you edit either."
        echo "SUITE_EMBEDDING_DIM=$EMBEDDING_DIM"
        echo "# Per-tier user-selectable model presets (JSON arrays of preset names)."
        echo "# Empty → the tier's model is shown to the user but not changeable by"
        echo "# them. Fill a list to let users switch their own tier via /config or the"
        echo "# webapp, e.g. SUITE_SELECTABLE_PRESETS_PRO=[\"gpt-pro\",\"claude-opus\"]."
        echo "SUITE_SELECTABLE_PRESETS_PRO=[]"
        echo "SUITE_SELECTABLE_PRESETS_BALANCED=[]"
        echo "SUITE_SELECTABLE_PRESETS_LITE=[]"
        echo
        echo "# --- Channel ---"
        echo "SUITE_TELEGRAM_BOT_TOKEN=$TELEGRAM"
        echo "# KakaoTalk (optional, 2nd chatbot channel). Egress-only pull"
        echo "# consumer behind the deploy/kakao-relay Cloudflare Worker + a"
        echo "# Cloudflare Queue (deploy that separately — see its README)."
        echo "# Valkey is on by default (compose -> redis://valkey:6379/1), which"
        echo "# also backs Kakao's registry; only set SUITE_VALKEY_URL to override."
        echo "# (Valkey is Redis-wire-compatible — the URL scheme stays redis://.)"
        echo "# SUITE_VALKEY_URL=redis://valkey:6379/1"
        echo "# SUITE_KAKAO_CF_ACCOUNT_ID="
        echo "# SUITE_KAKAO_CF_QUEUE_ID="
        echo "# SUITE_KAKAO_CF_API_TOKEN="
        echo "# Outbound images only (presigned R2); inbound reuse the file store."
        echo "# SUITE_KAKAO_R2_ENDPOINT_URL="
        echo "# SUITE_KAKAO_R2_BUCKET="
        echo "# SUITE_KAKAO_R2_ACCESS_KEY_ID="
        echo "# SUITE_KAKAO_R2_SECRET_ACCESS_KEY="
        echo
        echo "# --- Web search (research agent) ---"
        echo "# Backend: searxng | brave | kagi. brave/kagi use the API key below;"
        echo "# an unset key falls back to SearXNG (logged)."
        echo "SUITE_WEB_SEARCH_BACKEND=$WEB_BACKEND"
        if [[ "$SEARXNG_URL" == "$BUNDLED_SEARXNG_URL" ]]; then
            echo "# bundled SearXNG — prod.sh auto-adds '--profile search' on start/restart."
            echo "# deploy/searxng/settings.yml enables the json format + GET method the"
            echo "# research agent needs (the stock image defaults to html/POST → 403)."
            echo "# SEARXNG_SECRET overrides the instance secret_key (compose passes it"
            echo "# through). Only emitted for the bundled instance; an external SearXNG"
            echo "# is the operator's to configure."
            echo "SEARXNG_SECRET=$(gen 32)"
        fi
        echo "SUITE_SEARXNG_URL=$SEARXNG_URL"
        [[ -n "$BRAVE_KEY" ]] && echo "SUITE_BRAVE_API_KEY=$BRAVE_KEY"
        [[ -n "$KAGI_KEY" ]] && echo "SUITE_KAGI_API_KEY=$KAGI_KEY"
        echo
        echo "# --- md_converter LLM-vision OCR (optional) ---"
        echo "# Set KEY + MODEL to OCR images embedded in PDF/DOCX/PPTX/XLSX (and"
        echo "# scanned PDFs). Dedicated OpenAI-compatible provider, separate from the"
        echo "# router's presets. Leave empty to keep image handling metadata-only."
        echo "# SUITE_MD_OCR_API_KEY="
        echo "# SUITE_MD_OCR_MODEL=gpt-4o"
        echo "# SUITE_MD_OCR_BASE_URL="
        echo "# SUITE_MD_OCR_PROMPT="
    } > "$OUT"
    chmod 600 "$OUT"
    # Always (re)generate the Caddyfile for this mode — one code path; the env's
    # CADDYFILE_HOST_PATH (written above) points compose's caddy mount here. The
    # committed deploy/Caddyfile remains the localhost default for a bare compose.
    EDGE_MODE="$EDGE_MODE" PUBLIC_DOMAIN="$PUBLIC_DOMAIN" WEBAPP_DOMAIN="$WEBAPP_DOMAIN" \
        EDGE_SCHEME="$EDGE_SCHEME" PUBLIC_IP="$PUBLIC_IP" \
        ROUTER_HTTPS_PORT="$ROUTER_HTTPS_PORT" WEBAPP_HTTPS_PORT="$WEBAPP_HTTPS_PORT" \
        scripts/render-caddyfile.sh > "$CADDYFILE_GENERATED"
    # Repoint default + default_embedding at the chosen provider via the overlay
    # (clobber-safe). Skipped for `custom` — that operator owns the overlay.
    if [[ "$PROVIDER" != "custom" ]]; then generate_overlay; fi
    # Invitation tokens are the ONE thing not written above: they're single-use
    # and minted fresh on every start/restart by refresh_invitations(), which is
    # the single source. Seed them once here too, so a build-then-stop/exit (no
    # compose action) still leaves a complete, registerable env file.
    refresh_invitations

    echo
    echo "Wrote $OUT (chmod 600); generated $CADDYFILE_GENERATED (EDGE_MODE=$EDGE_MODE)."
    if [[ -n "$PUBLIC_DOMAIN" ]]; then
        echo "  edge [domain]: admin/router=$EDGE_SCHEME://$PUBLIC_DOMAIN  webapp=$EDGE_SCHEME://$WEBAPP_DOMAIN"
        [[ "$EDGE_SCHEME" == "http" ]] && \
            echo "        (domain: Caddy serves plain HTTP — TLS terminated upstream; clients still use https)"
    fi
    if [[ -n "$PUBLIC_IP" ]]; then
        local ROUTER_IP_ADDR="https://$PUBLIC_IP"
        [[ "$ROUTER_HTTPS_PORT" != "443" ]] && ROUTER_IP_ADDR="https://$PUBLIC_IP:$ROUTER_HTTPS_PORT"
        echo "  edge [bare IP]: admin/router=$ROUTER_IP_ADDR  webapp=https://$PUBLIC_IP:$WEBAPP_HTTPS_PORT"
        echo "        (https via Caddy's internal CA + default_sni — browsers warn until you trust"
        echo "         Caddy's root CA; the published ports ($ROUTER_HTTPS_PORT + $WEBAPP_HTTPS_PORT) — open them on any firewall)"
    fi
    echo "  provider: $PROVIDER   tiers: lite=$PRESET_LITE balanced=$PRESET_BALANCED pro=$PRESET_PRO"
    echo "  embedding: $PRESET_EMBEDDING (dim $EMBEDDING_DIM)"
    [[ $GENERATED_PW -eq 1 ]] && echo "  generated admin password: $ADMIN_PW   (save it!)"
    if [[ $REUSED -gt 0 ]]; then
        echo "  reused $REUSED volume-baked secret(s) from the previous $OUT"
        echo "        (PG/SUITE DB passwords, S3 keys — kept so they still match the"
        echo "        surviving data volumes; a fresh value would fail auth. Use"
        echo "        'reset' to wipe volumes AND mint new ones together.)"
    fi
    # Internal-CA TLS warning for a localhost/LAN DOMAIN served by Caddy (a public
    # domain over http means TLS is upstream, so no Caddy cert at all).
    if [[ -n "$PUBLIC_DOMAIN" && "$EDGE_SCHEME" == "https" ]]; then
        case "$PUBLIC_DOMAIN" in
            localhost|*.localhost|127.*|10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[01].*)
                echo "  NOTE: domain '$PUBLIC_DOMAIN' → Caddy serves internal-CA / self-signed TLS"
                echo "        (browsers warn until you trust Caddy's root CA — see"
                echo "        docs/backplaned/deployment.md). A public domain resolving here gets"
                echo "        automatic Let's Encrypt TLS instead." ;;
        esac
    fi
    if [[ "$PROVIDER" == "custom" ]]; then
        echo "  NOTE: custom — tiers point at presets: lite=$PRESET_LITE"
        echo "        balanced=$PRESET_BALANCED pro=$PRESET_PRO. Define them via a"
        echo "        deploy/presets.custom.jsonc overlay or the admin webUI (/admin),"
        echo "        and set the provider key(s) they reference. The bundled"
        echo "        'default' resolves to Gemini until repointed."
    elif [[ -z "$PROVIDER_KEY" ]]; then
        echo "  WARNING: $KEY_VAR is empty — set it before deploying."
    fi
    if [[ "$PROVIDER" == "anthropic" ]]; then
        echo "  NOTE: Anthropic has no embeddings; memory/knowledge-base use OpenAI"
        echo "        ($EMBED_MODEL via env://$EMBED_KEY_VAR), pinned to dim $EMBEDDING_DIM."
    fi
    if [[ -n "$EMBED_KEY_VAR" && "$EMBED_KEY_VAR" != "$KEY_VAR" && -z "$EMBED_KEY" ]]; then
        echo "  WARNING: $EMBED_KEY_VAR is empty — embeddings (memory/KB) will 401 until set."
    fi
    [[ -z "$TELEGRAM" ]] && echo "  WARNING: SUITE_TELEGRAM_BOT_TOKEN is empty — the chatbot won't poll Telegram."
    [[ "$SEARXNG_URL" == "$BUNDLED_SEARXNG_URL" ]] && echo "  search: bundled SearXNG (compose 'search' profile)"
    echo "  mcp bridge: enabled (compose 'mcp' profile) — configure servers in the admin UI"
    return 0  # don't let a false [[ ]] above become build_env's (set -e) exit
}

# ---------------------------------------------------------------------------
# Search-profile detection — read SUITE_SEARXNG_URL from the env FILE (not the
# prompt answer), so the `search` profile is added correctly even when the
# env-build step is skipped and an earlier-built file is reused.
# ---------------------------------------------------------------------------
env_searxng_url() {  # echo SUITE_SEARXNG_URL from $OUT (empty if unset/missing)
    [[ -f "$OUT" ]] || return 0
    sed -n 's/^SUITE_SEARXNG_URL=//p' "$OUT" | tail -n1
}

_INVITE_HEADER="# --- Agent invitation tokens (registered by the compose 'bootstrap' service) ---"

# Invitation tokens are SINGLE-USE: each launch consumes them at onboard, so
# the next launch needs FRESH ones (the router now allows idempotent
# re-onboard with a *new* invitation — see bp_router/api/onboard.py). Rewrite
# just the `*_INVITATION` lines in the existing env file (strip the old block,
# re-append a freshly-generated one) so start/restart always ships unused
# tokens — without rebuilding the whole env. The agents read these via compose
# interpolation and `bootstrap` registers them, so both see the same value.
refresh_invitations() {
    local tmp
    tmp="$(mktemp)"
    # Drop the invitation header (fixed-string whole-line match — it contains
    # `()`/`'` regex metachars) AND every *_INVITATION= line, then re-append a
    # fresh block. Everything else is kept byte-for-byte.
    grep -vxF "$_INVITE_HEADER" "$OUT" \
        | grep -vE "^[A-Z_]*_INVITATION=" > "$tmp" || true
    # Trim trailing blank lines so they don't accumulate across launches.
    sed -i -e :a -e '/^\n*$/{$d;N;ba}' "$tmp" 2>/dev/null || true
    {
        echo
        echo "$_INVITE_HEADER"
        scripts/register-invitations.sh --gen
    } >> "$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$OUT"
    TOKENS_MINTED=1
    echo "  refreshed agent invitation tokens (single-use — fresh per launch)"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
echo "Build the env file ($OUT)? Needed for a first deploy or to change vars."
echo "  (n reuses the existing file — just run a compose action.)"
ask BUILD_CHOICE "Build env? [y/N]" "n"
case "${BUILD_CHOICE,,}" in
    y|yes)
        if [[ -f "$OUT" ]]; then
            ask OVERWRITE "  $OUT exists — overwrite? [y/N]" "n"
            if yesish "$OVERWRITE"; then build_env; else echo "  keeping existing $OUT."; fi
        else
            build_env
        fi ;;
    n|no|"") : ;;
    *) echo "invalid choice: $BUILD_CHOICE" >&2; exit 1 ;;
esac

# Any compose action needs the env file to exist.
if [[ ! -f "$OUT" ]]; then
    echo "no env file at $OUT — re-run and choose to build it (first deploy)." >&2
    exit 1
fi

# The router bind-mounts deploy/presets.custom.jsonc (operator preset overlay).
# It's gitignored, so seed an empty no-op copy from the .example if absent —
# otherwise Docker would create a directory at the bind source and the router
# couldn't read it. Operators edit the real file to override/add presets.
OVERLAY="deploy/presets.custom.jsonc"
if [[ ! -f "$OVERLAY" && -f "$OVERLAY.example" ]]; then
    cp "$OVERLAY.example" "$OVERLAY"
    echo "  seeded $OVERLAY (empty overlay; edit it to override/add presets)."
fi

# Resolve compose args once (base + auto profiles from the env file).
CARGS=(-f "$COMPOSE_FILE" --env-file "$OUT")
# Pure bare-IP edge: layer the override that publishes ONLY the dedicated ports
# (ROUTER_HTTPS_PORT + WEBAPP_HTTPS_PORT), dropping the unused domain 80/443.
# `both` keeps 80/443 (it serves the domain too); `domain` never had IP ports.
if [[ "$(env_val EDGE_MODE)" == "ip" ]]; then
    CARGS+=(-f "$IP_PORTS_OVERRIDE")
    echo "  (bare-IP edge: dropping domain ports 80/443; publishing only" \
         "${ROUTER_HTTPS_PORT:-$(env_val ROUTER_HTTPS_PORT)} +" \
         "${WEBAPP_HTTPS_PORT:-$(env_val WEBAPP_HTTPS_PORT)})"
fi
if [[ "$(env_searxng_url)" == "$BUNDLED_SEARXNG_URL" ]]; then
    CARGS+=(--profile search)
    echo "  (search profile auto-enabled: SUITE_SEARXNG_URL=$BUNDLED_SEARXNG_URL)"
fi
# Run the MCP bridge whenever its secret is configured (prod.sh always generates
# it). Gated so a bare `docker compose up` without the secret won't start it.
if [[ -n "$(env_val MCP_BRIDGE_SECRET)" ]]; then
    CARGS+=(--profile mcp)
    echo "  (mcp profile auto-enabled: MCP_BRIDGE_SECRET is set)"
fi

echo
echo "Action:"
echo "  1) start        (docker compose up -d)"
echo "  2) restart      (recreate containers)"
echo "  3) stop         (docker compose down — keeps data volumes)"
echo "  4) reset        (down -v — DELETES the DB + all data volumes; full fresh start)"
echo "  5) exit         (do nothing)"
ask ACTION "Choose 1-5" "1"

# start / restart can optionally rebuild images from this source first.
maybe_build_flag() {
    ask REBUILD "  Rebuild images from this source first? [y/N]" "n"
    yesish "$REBUILD" && printf '%s' "--build"
    return 0
}

case "${ACTION,,}" in
    1|start)
        BUILD_FLAG="$(maybe_build_flag)"
        [[ "$TOKENS_MINTED" == "1" ]] || refresh_invitations
        echo; echo "+ docker compose ${CARGS[*]} up -d ${BUILD_FLAG}"
        exec docker compose "${CARGS[@]}" up -d ${BUILD_FLAG:+$BUILD_FLAG} ;;
    2|restart)
        BUILD_FLAG="$(maybe_build_flag)"
        [[ "$TOKENS_MINTED" == "1" ]] || refresh_invitations
        # `up -d --force-recreate` recreates ALL containers (a true restart);
        # --build first when rebuilding images from this source.
        echo; echo "+ docker compose ${CARGS[*]} up -d --force-recreate ${BUILD_FLAG}"
        exec docker compose "${CARGS[@]}" up -d --force-recreate ${BUILD_FLAG:+$BUILD_FLAG} ;;
    3|stop)
        echo; echo "+ docker compose ${CARGS[*]} down"
        exec docker compose "${CARGS[@]}" down ;;
    4|reset)
        # `down -v` ALSO removes named volumes — the Postgres DB (agent rows,
        # users, tasks), Valkey, SeaweedFS blobs, LanceDB, and every agent's
        # persisted credentials — for a genuine clean slate. (Normal
        # start/restart no longer needs this: invitations are refreshed each
        # launch and the router allows idempotent re-onboard, so agents
        # recover across redeploys. Use reset when you want to wipe DATA.)
        # Destructive — confirm.
        echo
        echo "  This DELETES ALL DATA: Postgres (users/tasks/agents), Valkey,"
        echo "  object store, LanceDB, and agent credentials. Irreversible."
        ask CONFIRM "  Type 'reset' to confirm" ""
        if [[ "$CONFIRM" == "reset" ]]; then
            echo; echo "+ docker compose ${CARGS[*]} down -v"
            exec docker compose "${CARGS[@]}" down -v
        else
            echo "  aborted — nothing deleted."
        fi ;;
    5|exit|"")
        echo "nothing to do." ;;
    *) echo "invalid choice: $ACTION" >&2; exit 1 ;;
esac
