#!/usr/bin/env bash
#
# scripts/render-caddyfile.sh — emit the edge Caddyfile for the configured
# EDGE_MODE to STDOUT. `scripts/prod.sh` always runs this when it (re)builds the
# env file, writing the result to deploy/Caddyfile.generated and pointing
# CADDYFILE_HOST_PATH at it (the compose `caddy` service bind-mounts that path).
# The committed deploy/Caddyfile stays the localhost default for a bare
# `docker compose up` run WITHOUT prod.sh.
#
# Generating the file (instead of env-interpolating one Caddyfile) is what lets
# a single deploy serve TWO identities at once — a public DOMAIN *and* a bare
# LAN IP (EDGE_MODE=both) — each with the right TLS, which `{$VAR}` placeholders
# in a single static site block cannot express.
#
# Driven entirely by env vars so it is unit-testable in isolation:
#   EDGE_MODE          domain | ip | both              (default: domain)
#   PUBLIC_DOMAIN      router + admin UI host           (domain, both)
#   WEBAPP_DOMAIN      browser-channel host             (domain, both)
#   EDGE_SCHEME        https | http                     (domain origin scheme)
#   PUBLIC_IP          bare-IP identity (IPv4 literal)  (ip, both)
#   WEBAPP_HTTPS_PORT  webapp's own https port for the IP (ip, both; default 8443)
#
# Invariants this enforces (matching prod.sh's prompts):
#   * A bare IP is ALWAYS https, with `tls internal` + a global `default_sni`.
#     A public IP otherwise "qualifies" for a public cert, so Caddy's default
#     issuer asks Let's Encrypt — which REFUSES to issue for an IP literal,
#     leaving :443 certless. And an IP client sends NO SNI (SNI carries only
#     hostnames), so behind Docker NAT Caddy can't pick a cert without a named
#     default → handshake `tls: internal error` (browser ERR_SSL_PROTOCOL_ERROR).
#   * `http` at the origin is only valid for a DOMAIN — it means TLS is
#     terminated UPSTREAM (Cloudflare Tunnel / external LB), so Caddy serves
#     plain HTTP and disables automatic HTTPS. (The PUBLIC scheme stays https.)
#
set -euo pipefail

EDGE_MODE="${EDGE_MODE:-domain}"
EDGE_SCHEME="${EDGE_SCHEME:-https}"
WEBAPP_HTTPS_PORT="${WEBAPP_HTTPS_PORT:-8443}"

die() { echo "render-caddyfile: $*" >&2; exit 1; }

want_domain=0 want_ip=0
case "$EDGE_MODE" in
    domain) want_domain=1 ;;
    ip)     want_ip=1 ;;
    both)   want_domain=1; want_ip=1 ;;
    *) die "invalid EDGE_MODE '$EDGE_MODE' (expected: domain | ip | both)" ;;
esac

if [[ $want_domain -eq 1 ]]; then
    [[ -n "${PUBLIC_DOMAIN:-}" ]] || die "PUBLIC_DOMAIN is required for EDGE_MODE=$EDGE_MODE"
    [[ -n "${WEBAPP_DOMAIN:-}" ]] || die "WEBAPP_DOMAIN is required for EDGE_MODE=$EDGE_MODE"
    case "$EDGE_SCHEME" in
        https|http) ;;
        *) die "EDGE_SCHEME must be 'https' or 'http' (got '$EDGE_SCHEME')" ;;
    esac
fi
if [[ $want_ip -eq 1 ]]; then
    [[ "${PUBLIC_IP:-}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] \
        || die "PUBLIC_IP must be an IPv4 literal for EDGE_MODE=$EDGE_MODE (got '${PUBLIC_IP:-}')"
    [[ "$WEBAPP_HTTPS_PORT" =~ ^[0-9]+$ ]] \
        || die "WEBAPP_HTTPS_PORT must be numeric (got '$WEBAPP_HTTPS_PORT')"
    [[ "$WEBAPP_HTTPS_PORT" != "443" ]] \
        || die "WEBAPP_HTTPS_PORT must differ from 443 (the IP router's port) — use e.g. 8443"
fi

# Reverse-proxy bodies shared by the domain and IP site blocks. Tab-indented so
# the emitted Caddyfile reads naturally inside its `{ }`.
router_body() {
    cat <<'EOF'
	# Router: HTTP API (/v1/*), health, metrics, OpenAPI, and the admin UI
	# (/admin/*). The /v1/agent WebSocket upgrade is proxied transparently.
	@router path /v1/* /admin* /healthz /readyz /metrics /docs /openapi.json
	reverse_proxy @router router:8000

	# Bare host → admin UI login.
	redir / /admin/login
EOF
}

webapp_body() {
    cat <<'EOF'
	# Browser channel — its own host because it serves from / (login, /chat/*,
	# /files/*), which would collide with the router's /admin. flush_interval -1
	# disables buffering so the chat SSE progress stream flushes immediately.
	reverse_proxy webapp:8002 {
		flush_interval -1
	}
EOF
}

# --- Header ----------------------------------------------------------------
cat <<EOF
# Edge reverse proxy — GENERATED by scripts/render-caddyfile.sh (EDGE_MODE=$EDGE_MODE).
#
# Do NOT edit by hand — re-run scripts/prod.sh (or scripts/render-caddyfile.sh)
# to regenerate. The committed deploy/Caddyfile is the localhost default for a
# bare \`docker compose up\` without prod.sh. See docs/backplaned/deployment.md
# "Edge / reverse proxy (Caddy)".
EOF

# --- Global options (only with a bare IP) ----------------------------------
if [[ $want_ip -eq 1 ]]; then
    cat <<EOF

{
	# Bare-IP https: an IP client sends no SNI (SNI carries only hostnames), and
	# behind Docker's port publishing Caddy sees the container IP, not the cert
	# SAN — so it can't match a cert without a named default. default_sni picks
	# the IP's internal-CA cert. (Domain connections send SNI and are matched by
	# host, so this is inert for them.)
	default_sni $PUBLIC_IP
}
EOF
fi

# --- Domain identity (EDGE_MODE=domain|both) -------------------------------
# https → Caddy auto-provisions TLS (Let's Encrypt for a public name; internal
# CA for localhost / *.localhost / private names). http → TLS terminated
# upstream; Caddy serves plain HTTP and disables automatic HTTPS.
if [[ $want_domain -eq 1 ]]; then
    cat <<EOF

$EDGE_SCHEME://$PUBLIC_DOMAIN {
$(router_body)
}

$EDGE_SCHEME://$WEBAPP_DOMAIN {
$(webapp_body)
}
EOF
fi

# --- Bare-IP identity (EDGE_MODE=ip|both) ----------------------------------
# Always https via the internal CA (see the header rationale). The webapp gets
# its OWN https port because there is no app.<ip> hostname to virtual-host on.
if [[ $want_ip -eq 1 ]]; then
    cat <<EOF

https://$PUBLIC_IP {
	# Pin the internal CA — Let's Encrypt refuses to issue for an IP literal, so
	# the default issuer would leave :443 certless.
	tls internal
$(router_body)
}

https://$PUBLIC_IP:$WEBAPP_HTTPS_PORT {
	tls internal
$(webapp_body)
}
EOF
fi
